#! perl

use v5.20;
use common::sense;

our @resources = (
      qw(
          background foreground cursor
          mouse_background mouse_foreground
          highlight border
          font geometry
      ),
      map { "color$_" } 0..15
    );

sub on_start {
    my %fallbacks = (
        border => "background",
        cursor => "foreground");

    for (@resources) {
        my $val = $TERM->x_resource($_);
        my $default = $TERM->x_resource($fallbacks{$_});
        if (not $val and $default){
            $val = $default
        }
        say "$_: " . $val;
    }
    exit;
}
